[build]
target = "avr-atmega328p.json"

[target.'cfg(target_arch = "avr")']
runner = "ravedude nano -cb 115200 -P COM4"
#runner = "ravedude nano -cb 57600 -P COM7"
#runner = "ravedude nano-new -cb 115200 -P COM3"
# 57600 15200
#runner = "avrdude -c arduino -p m328p -P COM3 -b 115200 -U flash:w:\"C:\\Users\\Gabriel\\Workspace\\Lödöl\\rust-x-arduino\\target\\avr-atmega328p\\debug\\rust-x-arduino.hex\":a #"
#rs\Gabriel\AppData\Local\Arduino15\packages\arduino\tools\avrdude\6.3.0-arduino17/etc/avrdude.conf" -
#v -V -patmega328p -carduino "-PCOM3" -b57600 -D "-Uflash:w:C:\Users\Gabriel\AppData\Local\arduino\sketches\4FDB8C5B337EBB4DB11721F5E4EBEDDE/board_tester.ino.hex:i"


[unstable]
build-std = ["core"]
